version: '3.2'
services:
  database:
    # Official Postgres image from DockerHub (we use the last version)
    image: 'postgres:latest'
    ports:
      - 54321:5432
    volumes:
      # In this example, we share the folder `db-data` in our root repository, with the default PostgreSQL data path.
      # It means that every time the repository is modifying the data inside
      # of `/var/lib/postgresql/data/`, automatically the change will appear in `db-data`.
      # You don't need to create the `db-data` folder. Docker Compose will do it for you.
      - ./db-data/:/var/lib/postgresql/data/
    environment:
      # This should be changed in production in order to take user and password from the env file
      POSTGRES_USER: nest-crud-username # The PostgreSQL user (useful to connect to the database)
      POSTGRES_PASSWORD: nest-crud-password # The PostgreSQL password (useful to connect to the database)
      POSTGRES_DB: nest-crud-database # The PostgreSQL default database (automatically created at first launch)
  nest-crud:
    build:
      context: .
      dockerfile: 'Dockerfile'
    ports:
      - '3000:3000'
